/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_maucout_version_console;

/**
 *
 * @author User
 */
public class Tuto extends javax.swing.JFrame {

    /**
     * Creates new form Tuto
     */
    public Tuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nvFacile = new javax.swing.JButton();
        nvMoyen = new javax.swing.JButton();
        nvDifficile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Bienvenue dans le Jeu.  \nLe but est simple:\nLorsque vous appuyez sur un boutton la ligne de couleur s'inverse.\n Il vous suffit donc de colorier toute la grille en une couleure\nPour commencer le jeu il vous suffit de cliauer sur une difficulté");
        jScrollPane1.setViewportView(jTextArea1);

        nvFacile.setText("Facile");
        nvFacile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvFacileActionPerformed(evt);
            }
        });

        nvMoyen.setText("Moyen");
        nvMoyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvMoyenActionPerformed(evt);
            }
        });

        nvDifficile.setText("Difficile");
        nvDifficile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nvDifficileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(nvFacile)
                        .addGap(96, 96, 96)
                        .addComponent(nvMoyen)
                        .addGap(82, 82, 82)
                        .addComponent(nvDifficile)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nvFacile)
                    .addComponent(nvMoyen)
                    .addComponent(nvDifficile))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nvFacileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvFacileActionPerformed
        // TODO add your handling code here:
        
       FenetrePrincipale f = new FenetrePrincipale(4,4,10);
       f.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_nvFacileActionPerformed

    private void nvMoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvMoyenActionPerformed
        // TODO add your handling code here:
         FenetrePrincipale f = new FenetrePrincipale(20,20,20);
       f.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_nvMoyenActionPerformed

    private void nvDifficileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nvDifficileActionPerformed
        // TODO add your handling code here:
         FenetrePrincipale f = new FenetrePrincipale(30,30,20);
       f.setVisible(true);
       this.dispose();
      
    }//GEN-LAST:event_nvDifficileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton nvDifficile;
    private javax.swing.JButton nvFacile;
    private javax.swing.JButton nvMoyen;
    // End of variables declaration//GEN-END:variables
}
